# Documentation for branch policy: https://aka.ms/gim/docs/policy/branch-protection

name: Default branch protection policy 
description: Requires one reviewer for merges into main branch
resource: repository
where: 
configuration:
  branchProtectionRules:
    - branchNamePattern: "main"
      requiredApprovingReviewsCount: 1
      requireCodeOwnersReview: true
      requiresConversationResolution: true
      requiresStrictStatusChecks: true
      requiredStatusChecks: 
      - build (windows-latest)
      - build (ubuntu-22.04)
      - Analyze (cpp)
      - CodeQL
      - dependency-review
      restrictsReviewDismissals: true
      whoCanDismissReviews:
      - nofmaintainers
    - branchNamePattern: "active"
      requireCodeOwnersReview: true
      requiredApprovingReviewsCount: 0
      requiresConversationResolution: true
      requiresStrictStatusChecks: true
      requiredStatusChecks: 
      - build (windows-latest)
      - build (ubuntu-22.04)
      - Analyze (cpp)
      - CodeQL
      - dependency-review
