name: Build [CMake]

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build-types:
        required: false
        # Note the string here contains a JSON array. This is later converted to an array using fromJson.
        default: "[ 'Debug' ]"
        type: string
        description: 'The CMake build type (CMAKE_BUILD_TYPE) to run.'

jobs:
  build:
    name: cmake build
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        build-type: ${{ fromJson(inputs.build-types) }}
    runs-on: ${{ matrix.os }} 
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-types }}
