name: Build [CMake]

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build-types:
        required: false
        # Note the string here contains a JSON array. This is later converted to an array using fromJson.
        default: "[ 'Debug' ]"
        type: string
        description: 'The CMake build type (CMAKE_BUILD_TYPE) to run.'
      analyze-codeql:
        required: false
        default: true
        type: boolean

jobs:
  build:
    name: cmake build
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        build-type: ${{ fromJson(inputs.build-types) }}
        language: [ 'cpp' ]
    runs-on: ${{ matrix.os }} 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      if: inputs.analyze-codeql == true
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: CMake Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: CMake Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: CMake Test (ctest)
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-types }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
